# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('userid', models.CharField(max_length=120)),
                ('salary', models.CharField(max_length=120)),
            ],
        ),
    ]
