# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=120)),
                ('userid', models.CharField(max_length=120)),
            ],
        ),
    ]
