# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliedd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
