# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='uid',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
