# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180619_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='uid',
            field=models.CharField(max_length=120),
        ),
    ]
