# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20180619_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marksheets',
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='fullname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
