# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20180619_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marksheet',
        ),
    ]
