# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fro', models.CharField(max_length=120)),
                ('to', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=120)),
            ],
        ),
    ]
