# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
            ],
        ),
    ]
